// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iozlsdiuhawaeyyidijq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvemxzZGl1aGF3YWV5eWlkaWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTEyMTAsImV4cCI6MjA2MDIyNzIxMH0.2t8uPXEnq0gMApfXAItKKv1hoQhtLiNn_jKu0McngHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);